- title: UI & UX design
  caption: I enjoy designing interfaces from scratch or improving existing interfaces, and I love prototyping in Figma.

- title: Design Systems
  caption: I break down complex interfaces into small reusable parts, so it's easier to design and build.

- title: Front End Dev
  caption: I build fast, accessible, responsive websites and apps that look good across devices.
